### ISSUE TITLE
[support request] \set command for set builder notation

### ISSUE THREAD

**Issue by yuishin-kikuchi** [AlphaZTX/physics2#13]
I really like physics2.sty.
I would like \set{...} command for set builder notation.

x = \set{x > 2 | x\in \mathbf{R}}
produces
_x_ = {_x_ > 2 | _x_ ∈ **R**}

I read phy-braket.sty and I think this is a minor change of \braket of physics2.
Thanks.

**Comment by AlphaZTX** [comment]
Also, after the left brace and before right brace should also have \thinmuskip reserved. See The TeXbook.

**Comment by AlphaZTX** [comment]
> I read phy-braket.sty and I think this is a minor change of \braket of physics2.

It is not that easy actually. I feel sorry to tell that I cannot add this feature in time, but using `\ab\{<content>\}` is enough for your requirement.
