### ISSUE TITLE
[Bug] diagmat throws error when there is `\sqrt` used

### ISSUE THREAD

**Issue by UlyssesZh** [AlphaZTX/physics2#17]
```tex
\documentclass{article}
\usepackage{physics2}
\usephysicsmodule{diagmat}
\begin{document}
\[\pdiagmat{\sqrt{2},\sqrt{2}}\]
\end{document}
```
```
! Incomplete \iffalse; all text was ignored after line 5.
<inserted text> 
                \fi 
<*> test.tex
            
?
```

**Comment by AlphaZTX** [comment]
It takes time to fix. You can use `\sqrtsign#1` or `\root#1\of#2` instead of `\sqrt` before the next version is released.

In this version, the same error will arise when you put macros containing `\@ifnextchar` in the mandatory argument of `\diagmat`.

**Comment by AlphaZTX** [comment]
Fixed. See 058dddf.
