### ISSUE TITLE
Could the bracket module  be furthrer improved?

### ISSUE THREAD

**Issue by AstaSchnee** [AlphaZTX/physics2#19]
Thank you for the good package. For me, a convenient fucntion of bracket in the package physics is wanted. When using physics, if I input `\ketbra{\psi}`, it will output $|\psi\rangle\langle\psi|$. Similarly, if I input `\expval{O}{\psi}`, it will output $\langle\psi|O|\psi\rangle$. I wonder whether this function will be added to physics2?

**Comment by AlphaZTX** [comment]
@AstaSchnee The first feature will not be added unchanged. Maybe a new macro will be added to a new module. The second feature may be added to a new module in the future. By the way, I recommend to use ab.braket instead of braket.

**Comment by AstaSchnee** [comment]
> @AstaSchnee The first feature will not be added unchanged. Maybe a new macro will be added to a new module. The second feature may be added to a new module in the future. By the way, I recommend to use ab.braket instead of braket.

Thank you for your thoughtful reply！
