### ISSUE TITLE
[support request] 输入行/列向量的功能

### ISSUE THREAD

**Issue by xiamyphys** [AlphaZTX/physics2#20]
您好，希望能加入快速输入行/列向量的功能，比如`\pxmat{A}{3}{1}`虽然也输入的是列向量，但是有两个角标，希望能通过如xparse，或者`\ifstar\@pxmat\s@pxmat`等等方式加一个`\pxmat*`命令，输入去除掉另一个角标～
这里可以加一个o参数，来控制行还是列向量，`\pxmat*[h]{A}{3}`横向输入3个元素，`\pxmat*[v]{A}{3}`纵向输入3个元素.

当然，能够实现下图中快速输入这种AB不同下标矩阵就更好啦～
Thanks.

![CleanShot 2024-03-06 at 15 40 05@2x](https://github.com/AlphaZTX/physics2/assets/134639741/7790c6ac-7426-4156-9eac-058bd43e868a)

**Comment by AlphaZTX** [comment]
@xiamyphys 先mark一下，等不忙了加，但会用其他命令。另外，xmat这一部分打算加点新功能。

**Comment by AlphaZTX** [comment]
近期暂不实现。
