### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by Firestar-Reimu** [AlphaZTX/physics2#21]
1. ab.legacy的实现方式和ab有什么不同吗？为什么不推荐使用？
2. ab.braket和braket似乎只有<|和{}的区别，内部实现方式相同吗，未来是否考虑合并（而不是冲突），也就是同一个module，用两种括号都对？
3. 导数部分的问题已经在[这里](https://github.com/sjelatex/derivative/issues/16)提过了
4. 考虑出中文文档吗（可以考虑pull request）

**Comment by AlphaZTX** [comment]
@Firestar-Reimu 1. 我在代码文档里对 ab 的实现有解释。ab.legacy 是一些我不太希望直接加到 ab 的补充功能，反正我自己不用 ab.legacy。

2. 内部实现完全不同，有精力可以看看代码。这俩 module 不考虑合并，也不可能合并。你哪个用着舒服就用哪个，我自己更喜欢用 ab.braket。

**Comment by Firestar-Reimu** [comment]
1. 好吧，我个人是觉得 `\abs` `\norm` `\eval` 比 `\left| \right|` `\left\| \right\|` `\left. \right|` 要方便得多，既然这个和ab的原理相同（也就是比原来的physics好）我会选择使用的

又及：我发现`\abs`可以用`\ab| |`代替，同样还有`\norm >> \ab\| \|`，但我觉得还是`\abs \norm \eval`比较直观和方便

2. 那为什么要设计两个braket啊（笑）
3. 考虑出中文文档吗

**Comment by AlphaZTX** [comment]
@Firestar-Reimu 1. 可以用。

2. 不同用户使用习惯不同，就做了两份不同的。有人更喜欢用花括号指定参数，就用 braket；有人更喜欢形象的 <f|A|f>，就用 ab.braket。用哪个都可以，都足够 robust。

3. 暂时不考虑，并且也没有在这个 repo 里面加一份中文文档源码的计划（虽然我自己也更喜欢看中文文档）。当然，你如果感兴趣，可以翻译一份。如果翻译质量过得去，并且翻译版文档同样以 LPPL 协议发布，我会在 README 和用户手册中加上翻译版的链接。

4. physics2.sty 本体是一个简单的包管理器，从 TeX 用的内存中申请了几个寄存器。额外功能是对括号的简单封装（见用户手册）。计划加个调用 mleftright 包的选项，毕业了我再加进去。

**Comment by fiveseven-lambda** [comment]
> `\eval >> \ab |\delclose`

I don't understand this. Do you mean `\delopen.` and `\delclose|`?

**Comment by AlphaZTX** [comment]
> > `\eval >> \ab |\delclose`
> 
> I don't understand this. Do you mean `\delopen.` and `\delclose|`?

The usage `\ab.#1|` is illegal. `\eval{#1}` is equivalent to `\delopen.#1\delclose|`. I have edited his comment.
@fiveseven-lambda

**Comment by fiveseven-lambda** [comment]
@AlphaZTX Thank you. It helps me a lot.
