### ISSUE TITLE
Adding support for super-bra-ket notation

### ISSUE THREAD

**Issue by John-foobar-Doe** [AlphaZTX/physics2#23]
Hello, could you please add support for super-bra-ket notation (in either the `ab.braket` module or `braket` module), e.g., `\ket|\rho>>` to produce $`| \rho \rangle \rangle`$, and `\braket<<A|B>>` to produce $`\langle \langle A | B \rangle \rangle`$? This will be very helpful for quantum information related areas & topics, e.g., see https://en.wikipedia.org/wiki/Superoperator, https://en.wikipedia.org/wiki/Liouville_space, and https://arxiv.org/pdf/2003.11472#page=23.

Many thanks!

**Comment by AlphaZTX** [comment]
I’ll try in July. The syntax will be different from your sample.

**Comment by AlphaZTX** [comment]
@John-foobar-Doe 
It may be hard to produce delimiters more than one character like `<<` and `>>`. Do you think `\superbrabet<A|B>` for $\langle\langle A|B\rangle\rangle$ is acceptable?

**Comment by John-foobar-Doe** [comment]
> @John-foobar-Doe It may be hard to produce delimiters more than one character like `<<` and `>>`. Do you think `\superbrabet<A|B>` for ⟨⟨A|B⟩⟩ is acceptable?

Yes, it should be fine. Alternatively, will something like `\braket{<A}{B>}` be implementable?

**Comment by AlphaZTX** [comment]
@John-foobar-Doe It may be hard to be loaded in braket module directly. I'll try to find a way to implement this.

**Comment by John-foobar-Doe** [comment]
> I'll try to find a way to implement this.

No problem, and please feel free to choose any approach that is implementable and convenient for users to input/type.

**Comment by AlphaZTX** [comment]
I will not handle this issue. If you can handle yourself, please pull a request.

**Comment by John-foobar-Doe** [comment]
> I will not handle this issue. If you can handle yourself, please pull a request.

The super-bra-ket notation is implemented in https://ctan.org/pkg/phfqit (https://github.com/phfaist/phfqitltx), but there seems to be a conflict with the `ab.braket` module. So could you please at least make `physics2` compatible with the `phfqit` package?

Many thanks again!

**Comment by AlphaZTX** [comment]
No. In order to communicate your requirements better, please communicate in Chinese first if you can speak Chinese.
