### ISSUE TITLE
Complex custom order symbol not supported in ab.legacy 

### ISSUE THREAD

**Issue by fekete-d** [AlphaZTX/physics2#25]
If I want to set the order symbol when using the `ab.legacy` module, let's say to 'R', I can do so, according to the manual, by
```latex
\usephysicsmodule[order=R]{ab.legacy}
```
The order symbol will be a simple math mode italic 'R'. However, if I wanted to retain the calligraphy or still use the letter 'O' but with a different style, e.g., (blackboard) boldface, I would do the following:
```latex
\usephysicsmodule[order=\mathcal{R}]{ab.legacy}
% or
% \usephysicsmodule[order=\mathbb{O}]{ab.legacy}
```
Unfortunately, neither works and I get many errors (undefined control sequences, illegal parameters, runaway arguments, extra '}'s). 

One way to resolve this is to define a protected macro for the custom symbol and pass that as an argument, as follows:
```latex
\protected\def\myOrderSymbol{\mathcal{R}}
\usephysicsmodule[order=\myOrderSymbol]{ab.legacy}
```
Is there a way you could update the package to handle more complex order symbols automatically instead of this workaround (i.e., the second code block should work as expected)?

Thanks!

**Comment by AlphaZTX** [comment]
🫣😨😱 Oh my... Why does this happen? I'll try to fix it.

**Comment by AlphaZTX** [comment]
Only NFSS-related commands can reproduce this problem. Weird!

**Comment by AlphaZTX** [comment]
I didn't come up with some good ideas till now. Maybe after some days I will know how to fix the code in `physics2.sty`, line 56 to 60.

**Comment by muzimuzhi** [comment]
It seems `\protected@edef` does the trick.

Or, rewrite the processing of key-value package options in the new LaTeX approach, see `texdoc clsguide` (2024-09-15), sec. 4.4 "Creating and using keyval options" and `texdoc ltnews35`, sec. "A key/value approach to option handling".

```tex
\documentclass{article}
\usepackage{physics2}

\makeatletter
\def\phy@processkeyopt#1{\let\reserved@a\@empty%
  \protected@edef\reserved@a{\@ptionlist{\@currname.\@currext}}%
  \ExpandArgs{no}\phy@setkeys{#1}{\reserved@a}%
  \AtEndOfPackage{\let\@unprocessedoptions\relax}}
\makeatother

\usephysicsmodule[order=\mathcal{R}]{ab.legacy}\relax

\begin{document}
content
\end{document}
```

```diff
diff --git a/physics2-code.src.base.dtx b/physics2-code.src.base.dtx
index ea2d428..7f526fd 100644
--- a/physics2-code.src.base.dtx
+++ b/physics2-code.src.base.dtx
@@ -52,9 +52,8 @@
 \long\def\phy@define@key#1{\define@key{phy-#1}}
 \long\def\phy@setkeys#1{\setkeys{phy-#1}}
 \def\phy@processkeyopt#1{\let\reserved@a\@empty%
-  \edef\reserved@a{\@ptionlist{\@currname.\@currext}}%
-  \edef\reserved@a{\noexpand\phy@setkeys{#1}{\reserved@a}}%
-  \reserved@a
+  \protected@edef\reserved@a{\@ptionlist{\@currname.\@currext}}%
+  \ExpandArgs{no}\phy@setkeys{#1}{\reserved@a}%
   \AtEndOfPackage{\let\@unprocessedoptions\relax}}
 %    \end{macrocode}
 % We use almost the same way to load \pkg{physics2} modules as \LaTeXe\ kernel
```

BTW better to use temp macros `\@tempa`, `\@tempb`, and `\@tempc` (see for example `texdoc macros2e`) in package code, and reserve uses of `\reserved@a`, etc. to the LaTeX kernel only.

**Comment by AlphaZTX** [comment]
@muzimuzhi Thanks! That's perfect!
