### ISSUE TITLE
Error with \abs{1+\frac{x}{x}}}

### ISSUE THREAD

**Issue by elyurn** [AlphaZTX/physics2#4]
When using ab.legacy, the following line doesn't work:
\[ \abs{1+\frac{x}{x}}} \]

However, 
\[ \abs{\frac{x}{x}} \]
does work.

**Comment by mbertucci47** [comment]
You have one too many `}` but still it does produce an error.

**Comment by elyurn** [comment]
Yes, sorry for the typo. It seems that the problem also occurs with ab, for example with 
\pab{1-\frac{1}{x}}

**Comment by AlphaZTX** [comment]
Fixed in #5.

Please notice the usage of commands like `\abs` is changed. See the documentation for more. You can compile `physics2.tex` with `xelatex` or `lualatex` to get the PDF.
