### ISSUE TITLE
ab模块的括号匹配有问题

### ISSUE THREAD

**Issue by orbitoo** [AlphaZTX/physics2#6]
我写出了如下的代码:
```latex
\[
    \mathrm{HMAC}(K, M) = H\ab\Big[(K^+\oplus \mathrm{opad}) \parallel
    H\ab\big[(K^+\oplus \mathrm{ipad})\parallel M]].
\]
```
实际生成的公式为

![Snipaste_2023-04-02_01-43-24](https://user-images.githubusercontent.com/86230731/229306472-60a003b3-ccb9-4c01-b381-7ff096c60f29.png)

最右侧的方括号匹配的是左端的方括号, 即 `\ab\Big[`, 但实际生成的大小为 `\big` 的大小, 与内层的方括号大小一致.

**Comment by AlphaZTX** [comment]
此问题已解决，详见 #7。如果你觉得这个包还不错，欢迎给个小星星~

**Comment by orbitoo** [comment]
> 此问题已解决，详见 #7。如果你觉得这个包还不错，欢迎给个小星星~

starred already。
我想顺便问问关于数学环境写文字的事，文档不建议再使用\qq命令，那推荐的做法是什么呢?手动地使用\text并且补上前后的距离吗

**Comment by AlphaZTX** [comment]
> 文档不建议再使用\qq命令，那推荐的做法是什么呢？手动地使用 `\text` 并且补上前后的距离吗？

是的，同时也比较建议自己定义一些命令。如果命令不冲突的话，你也可以直接用 `qtext.legacy` 模块。但所有带 legacy 的模块都不推荐使用。

**Comment by orbitoo** [comment]
> > 文档不建议再使用\qq命令，那推荐的做法是什么呢？手动地使用 `\text` 并且补上前后的距离吗？
> 
> 是的，同时也比较建议自己定义一些命令。如果命令不冲突的话，你也可以直接用 `qtext.legacy` 模块。但所有带 legacy 的模块都不推荐使用。
> 
> 

谢谢你的解答♥️
